version: "2.1"
jobs:
  test:
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - checkout
      - run:
          name: install deps
          command: |
            sudo apt-get update
            sudo apt-get install -y gcc make cmake git binutils libc6-dev
      - run:
          command: make test
workflows:
  version: "2.1"
  test-workflow:
    jobs:
      - test
